-- =============================================================================
-- AgroGrade AI - PostgreSQL Database Schema
-- Optimized for REAL-TIME AI inference (dynamic analysis, not static data)
-- =============================================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "postgis";  -- For location/geography support

-- =============================================================================
-- 1. FARMERS TABLE - Core user data with location for regional crop patterns
-- =============================================================================
CREATE TABLE farmers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    phone TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE,
    password_hash TEXT NOT NULL,
    location GEOGRAPHY(POINT, 4326),  -- GPS coordinates (lat, long)
    address TEXT,
    region TEXT CHECK (region IN (
        'gujarat_cotton',
        'gujarat_groundnut',
        'punjab_wheat',
        'punjab_rice',
        'tamil_rice',
        'maharashtra_sugarcane',
        'karnataka_coffee',
        'andhra_cotton',
        'rajasthan_mustard',
        'up_wheat'
    )),
    farm_size_acres FLOAT,
    primary_crops TEXT[],  -- Array of crops farmer typically grows
    is_verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for faster phone lookups (login)
CREATE INDEX idx_farmers_phone ON farmers(phone);
CREATE INDEX idx_farmers_region ON farmers(region);

-- =============================================================================
-- 2. AI INFERENCE RESULTS - Stores DYNAMIC analysis from AI models
-- =============================================================================
CREATE TABLE ai_inferences (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    farmer_id UUID NOT NULL REFERENCES farmers(id) ON DELETE CASCADE,
    
    -- Image identification
    image_url TEXT NOT NULL,           -- Stored image path/URL
    image_hash TEXT NOT NULL,          -- SHA256 hash for duplicate detection
    image_metadata JSONB,              -- {width, height, format, size_bytes}
    
    -- DYNAMIC Crop Detection (not pre-defined)
    detected_crop TEXT NOT NULL,       -- Detected: cotton/wheat/rice/tomato/okra/potato/chilli
    crop_confidence FLOAT NOT NULL CHECK (crop_confidence BETWEEN 0 AND 1),
    
    -- DYNAMIC Disease Diagnosis (NULL if healthy)
    disease TEXT,                      -- Diagnosed disease name (dynamic from AI)
    disease_confidence FLOAT CHECK (disease_confidence BETWEEN 0 AND 1),
    severity_percent FLOAT CHECK (severity_percent BETWEEN 0 AND 100),  -- Lesion coverage %
    is_healthy BOOLEAN GENERATED ALWAYS AS (disease IS NULL) STORED,
    
    -- Quality Grading
    grade TEXT CHECK (grade IN ('A', 'B', 'C', 'D', 'Rejected')),
    grade_score FLOAT CHECK (grade_score BETWEEN 0 AND 100),
    
    -- Combined Trust Score (AI + Sensor fusion)
    trust_score FLOAT CHECK (trust_score BETWEEN 0 AND 100),
    price_multiplier FLOAT DEFAULT 1.0,  -- Based on grade/trust
    
    -- IoT Sensor Data (fused with visual analysis)
    sensor_data JSONB,  -- {
                        --   "soil_moisture": 68,
                        --   "soil_temperature": 28,
                        --   "nitrogen_ppm": 42,
                        --   "phosphorus_ppm": 38,
                        --   "potassium_ppm": 55,
                        --   "ph_level": 6.8,
                        --   "humidity": 72,
                        --   "sensor_timestamp": "2025-01-30T10:30:00Z"
                        -- }
    
    -- DYNAMIC Insights Array (generated by AI)
    insights JSONB NOT NULL DEFAULT '[]',  -- [
                                            --   {"type": "alert", "severity": "high", "message": "Early blight detected"},
                                            --   {"type": "recommendation", "message": "Apply neem oil spray"},
                                            --   {"type": "info", "message": "Soil moisture optimal"}
                                            -- ]
    
    -- Recommended Actions (auto-generated)
    remedies JSONB,  -- [{"type": "organic", "name": "Neem Oil", "instructions": "..."}]
    
    -- Processing metadata
    inference_time_ms INTEGER,          -- How long AI took to process
    model_version TEXT,                 -- AI model version used
    
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX idx_ai_inferences_farmer ON ai_inferences(farmer_id);
CREATE INDEX idx_ai_inferences_crop ON ai_inferences(detected_crop);
CREATE INDEX idx_ai_inferences_disease ON ai_inferences(disease) WHERE disease IS NOT NULL;
CREATE INDEX idx_ai_inferences_grade ON ai_inferences(grade);
CREATE INDEX idx_ai_inferences_created ON ai_inferences(created_at DESC);
CREATE INDEX idx_ai_inferences_hash ON ai_inferences(image_hash);  -- Duplicate detection

-- =============================================================================
-- 3. CROP-DISEASE MAPPING - Enables DYNAMIC routing of remedies
-- =============================================================================
CREATE TABLE crop_diseases (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    crop TEXT NOT NULL,
    disease TEXT NOT NULL,
    scientific_name TEXT,
    symptoms TEXT[],                    -- Array of symptom descriptions
    organic_remedies TEXT[] NOT NULL,
    chemical_remedies TEXT[],
    prevention_tips TEXT[],
    severity_thresholds JSONB NOT NULL DEFAULT '{"low": 15, "medium": 40, "high": 60}',
    spread_risk TEXT CHECK (spread_risk IN ('low', 'medium', 'high')),
    treatment_duration_days INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    UNIQUE(crop, disease)
);

CREATE INDEX idx_crop_diseases_crop ON crop_diseases(crop);

-- =============================================================================
-- 4. MARKETPLACE LISTINGS - Products with AI-verified quality
-- =============================================================================
CREATE TABLE marketplace_listings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    farmer_id UUID NOT NULL REFERENCES farmers(id) ON DELETE CASCADE,
    inference_id UUID REFERENCES ai_inferences(id),  -- Link to quality scan
    
    title TEXT NOT NULL,
    description TEXT,
    crop_type TEXT NOT NULL,
    variety TEXT,
    
    -- Quantity & Pricing
    quantity FLOAT NOT NULL,
    unit TEXT NOT NULL CHECK (unit IN ('kg', 'quintal', 'ton', 'piece', 'dozen')),
    price_per_unit FLOAT NOT NULL,
    minimum_order FLOAT,
    
    -- Quality verification
    grade TEXT CHECK (grade IN ('A', 'B', 'C')),
    trust_score FLOAT,
    is_verified BOOLEAN DEFAULT FALSE,
    verification_date TIMESTAMPTZ,
    
    -- Images
    images TEXT[] NOT NULL,  -- Array of image URLs
    
    -- Location
    pickup_location GEOGRAPHY(POINT, 4326),
    district TEXT,
    state TEXT,
    
    -- Status
    status TEXT DEFAULT 'active' CHECK (status IN ('draft', 'active', 'sold', 'expired', 'cancelled')),
    views_count INTEGER DEFAULT 0,
    inquiries_count INTEGER DEFAULT 0,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ
);

CREATE INDEX idx_listings_farmer ON marketplace_listings(farmer_id);
CREATE INDEX idx_listings_crop ON marketplace_listings(crop_type);
CREATE INDEX idx_listings_grade ON marketplace_listings(grade);
CREATE INDEX idx_listings_status ON marketplace_listings(status);
CREATE INDEX idx_listings_location ON marketplace_listings USING GIST(pickup_location);

-- =============================================================================
-- 5. IOT SENSORS - Registered sensors for farms
-- =============================================================================
CREATE TABLE iot_sensors (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    farmer_id UUID NOT NULL REFERENCES farmers(id) ON DELETE CASCADE,
    device_id TEXT UNIQUE NOT NULL,
    sensor_type TEXT NOT NULL CHECK (sensor_type IN ('soil', 'weather', 'crop_monitor')),
    location GEOGRAPHY(POINT, 4326),
    field_name TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    last_reading_at TIMESTAMPTZ,
    battery_level INTEGER CHECK (battery_level BETWEEN 0 AND 100),
    firmware_version TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================================================
-- 6. SENSOR READINGS - Time-series data from IoT devices
-- =============================================================================
CREATE TABLE sensor_readings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sensor_id UUID NOT NULL REFERENCES iot_sensors(id) ON DELETE CASCADE,
    
    -- Soil metrics
    soil_moisture FLOAT CHECK (soil_moisture BETWEEN 0 AND 100),
    soil_temperature FLOAT,
    nitrogen_ppm FLOAT,
    phosphorus_ppm FLOAT,
    potassium_ppm FLOAT,
    ph_level FLOAT CHECK (ph_level BETWEEN 0 AND 14),
    
    -- Weather metrics
    air_temperature FLOAT,
    humidity FLOAT CHECK (humidity BETWEEN 0 AND 100),
    rainfall_mm FLOAT,
    wind_speed FLOAT,
    
    -- Raw data
    raw_data JSONB,
    
    recorded_at TIMESTAMPTZ DEFAULT NOW()
);

-- Partition by time for better performance on time-series data
CREATE INDEX idx_sensor_readings_sensor ON sensor_readings(sensor_id);
CREATE INDEX idx_sensor_readings_time ON sensor_readings(recorded_at DESC);

-- =============================================================================
-- 7. TRANSACTIONS - Marketplace orders
-- =============================================================================
CREATE TABLE transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id UUID NOT NULL REFERENCES marketplace_listings(id),
    buyer_id UUID NOT NULL REFERENCES farmers(id),
    seller_id UUID NOT NULL REFERENCES farmers(id),
    
    quantity FLOAT NOT NULL,
    unit TEXT NOT NULL,
    price_per_unit FLOAT NOT NULL,
    total_amount FLOAT NOT NULL,
    
    status TEXT DEFAULT 'pending' CHECK (status IN (
        'pending', 'confirmed', 'paid', 'shipped', 'delivered', 'completed', 'cancelled', 'disputed'
    )),
    
    payment_method TEXT,
    payment_reference TEXT,
    
    delivery_address TEXT,
    expected_delivery_date DATE,
    actual_delivery_date DATE,
    
    buyer_rating INTEGER CHECK (buyer_rating BETWEEN 1 AND 5),
    seller_rating INTEGER CHECK (seller_rating BETWEEN 1 AND 5),
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_transactions_buyer ON transactions(buyer_id);
CREATE INDEX idx_transactions_seller ON transactions(seller_id);
CREATE INDEX idx_transactions_status ON transactions(status);

-- =============================================================================
-- 8. NOTIFICATIONS - User notifications
-- =============================================================================
CREATE TABLE notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    farmer_id UUID NOT NULL REFERENCES farmers(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK (type IN (
        'disease_alert', 'sensor_alert', 'market_update', 'order_update', 'price_alert', 'system'
    )),
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    data JSONB,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_notifications_farmer ON notifications(farmer_id);
CREATE INDEX idx_notifications_unread ON notifications(farmer_id, is_read) WHERE is_read = FALSE;

-- =============================================================================
-- SEED DATA: Common crop diseases for Gujarat region
-- =============================================================================
INSERT INTO crop_diseases (crop, disease, scientific_name, symptoms, organic_remedies, severity_thresholds) VALUES
-- Cotton diseases
('cotton', 'bacterial_blight', 'Xanthomonas citri pv. malvacearum', 
 ARRAY['Angular water-soaked lesions', 'Black arm on stems', 'Boll rot'],
 ARRAY['Copper hydroxide spray', 'Neem oil application', 'Crop rotation'],
 '{"low": 10, "medium": 30, "high": 50}'
),
('cotton', 'grey_mildew', 'Ramularia areola',
 ARRAY['Angular spots on leaves', 'White powdery growth underneath'],
 ARRAY['Sulfur dust application', 'Trichoderma spray', 'Improved drainage'],
 '{"low": 15, "medium": 35, "high": 55}'
),

-- Tomato diseases
('tomato', 'early_blight', 'Alternaria solani',
 ARRAY['Brown spots with concentric rings', 'Lower leaves affected first', 'Leaf yellowing'],
 ARRAY['Neem oil spray (5ml/L)', 'Copper fungicide', 'Trichoderma viride'],
 '{"low": 15, "medium": 40, "high": 60}'
),
('tomato', 'late_blight', 'Phytophthora infestans',
 ARRAY['Water-soaked lesions', 'White mold on underside', 'Rapid plant death'],
 ARRAY['Bordeaux mixture', 'Copper oxychloride', 'Remove infected plants'],
 '{"low": 10, "medium": 25, "high": 45}'
),
('tomato', 'leaf_curl', 'Tomato leaf curl virus',
 ARRAY['Upward curling leaves', 'Stunted growth', 'Yellowing'],
 ARRAY['Control whiteflies', 'Neem oil spray', 'Yellow sticky traps'],
 '{"low": 20, "medium": 45, "high": 70}'
),

-- Wheat diseases
('wheat', 'rust', 'Puccinia spp.',
 ARRAY['Orange-red pustules on leaves', 'Yellow streaks', 'Reduced grain filling'],
 ARRAY['Sulfur dust', 'Trichoderma spray', 'Resistant varieties'],
 '{"low": 10, "medium": 30, "high": 50}'
),
('wheat', 'powdery_mildew', 'Blumeria graminis',
 ARRAY['White powdery patches', 'Yellowing leaves', 'Reduced yield'],
 ARRAY['Sulfur spray', 'Neem oil', 'Improved air circulation'],
 '{"low": 15, "medium": 35, "high": 55}'
),

-- Rice diseases
('rice', 'blast', 'Magnaporthe oryzae',
 ARRAY['Diamond-shaped lesions', 'White to gray centers', 'Neck rot'],
 ARRAY['Trichoderma application', 'Silicon fertilizer', 'Balanced nitrogen'],
 '{"low": 10, "medium": 25, "high": 45}'
),
('rice', 'brown_spot', 'Cochliobolus miyabeanus',
 ARRAY['Brown oval spots', 'Yellow halo around spots', 'Seed discoloration'],
 ARRAY['Pseudomonas fluorescens', 'Potash application', 'Seed treatment'],
 '{"low": 15, "medium": 35, "high": 55}'
);

-- =============================================================================
-- FUNCTIONS & TRIGGERS
-- =============================================================================

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_farmers_updated_at
    BEFORE UPDATE ON farmers
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_listings_updated_at
    BEFORE UPDATE ON marketplace_listings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_transactions_updated_at
    BEFORE UPDATE ON transactions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- =============================================================================
-- VIEWS - Useful aggregations
-- =============================================================================

-- Disease statistics by region
CREATE VIEW regional_disease_stats AS
SELECT 
    f.region,
    ai.detected_crop,
    ai.disease,
    COUNT(*) as case_count,
    AVG(ai.disease_confidence) as avg_confidence,
    AVG(ai.severity_percent) as avg_severity
FROM ai_inferences ai
JOIN farmers f ON ai.farmer_id = f.id
WHERE ai.disease IS NOT NULL
    AND ai.created_at > NOW() - INTERVAL '30 days'
GROUP BY f.region, ai.detected_crop, ai.disease
ORDER BY case_count DESC;

-- Farmer dashboard stats
CREATE VIEW farmer_stats AS
SELECT 
    f.id as farmer_id,
    f.name,
    COUNT(DISTINCT ai.id) as total_scans,
    COUNT(DISTINCT CASE WHEN ai.is_healthy = false THEN ai.id END) as disease_detections,
    COUNT(DISTINCT ml.id) as active_listings,
    COALESCE(SUM(t.total_amount) FILTER (WHERE t.seller_id = f.id AND t.status = 'completed'), 0) as total_earnings
FROM farmers f
LEFT JOIN ai_inferences ai ON f.id = ai.farmer_id
LEFT JOIN marketplace_listings ml ON f.id = ml.farmer_id AND ml.status = 'active'
LEFT JOIN transactions t ON f.id = t.seller_id
GROUP BY f.id, f.name;
